# Generated by Django 4.2.3 on 2023-08-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certification',
            field=models.CharField(blank=True, choices=[('KCPE', 'Kenya Certificate of Primary Education (KCPE)'), ('KCSE', 'Kenya Certificate of Secondary Education (KCSE)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_ended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='grade_attained',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='name_of_the_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
