# Generated by Django 4.2.3 on 2023-08-15 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume_certification_resume_date_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='date_started',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='grade_attained',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='index_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name_of_the_school',
        ),
        migrations.CreateModel(
            name='BasicEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_school', models.CharField(blank=True, max_length=255, null=True)),
                ('index_number', models.CharField(blank=True, max_length=20, null=True)),
                ('certification', models.CharField(blank=True, choices=[('KCPE', 'Kenya Certificate of Primary Education (KCPE)'), ('KCSE', 'Kenya Certificate of Secondary Education (KCSE)')], max_length=10, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('grade_attained', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
