# Generated by Django 4.2.3 on 2023-08-15 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_resume_certification_remove_resume_date_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiceducation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_education', to=settings.AUTH_USER_MODEL),
        ),
    ]
