# Generated by Django 4.2.3 on 2023-08-15 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_basiceducation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherStudiesCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='basiceducation',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FurtherStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_undertaken', models.CharField(blank=True, max_length=100, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('certifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.furtherstudiescertification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_studies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
