# Generated by Django 4.2.3 on 2023-08-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_furtherstudiescertification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifyingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('certifying_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.certifyingbody')),
            ],
        ),
    ]
