# Generated by Django 4.2.3 on 2023-08-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_certification_date_attained_certification_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
