# Generated by Django 4.2.3 on 2023-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
