# Generated by Django 4.2.3 on 2023-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_workexperience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
