# Generated by Django 4.2.3 on 2023-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_professionalsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_certificate',
        ),
        migrations.AddField(
            model_name='basiceducation',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/{user_id}/{basic_education_id}/'),
        ),
        migrations.AddField(
            model_name='furtherstudies',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/{user_id}/{further_studies_id}/'),
        ),
        migrations.AddField(
            model_name='membership',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/{user_id}/memberships/'),
        ),
    ]
