# Generated by Django 4.2.3 on 2023-08-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_membership_membership_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('system admin', 'system admin'), ('hr', 'hr'), ('hr interns', 'hr interns'), ('hr attachment', 'hr attachment')], max_length=20, null=True),
        ),
    ]
