# Generated by Django 4.2.3 on 2023-08-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.CharField(blank=True, choices=[('system admin', 'system admin'), ('hr', 'hr'), ('hr interns', 'hr interns'), ('hr attachment', 'hr attachments')], max_length=20, null=True),
        ),
    ]
