# Generated by Django 4.2.3 on 2023-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_educationallevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationallevel',
            name='index',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
    ]
