# Generated by Django 4.2.3 on 2023-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_educationallevel_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationallevel',
            name='index',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
