# Generated by Django 4.2.3 on 2023-09-26 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_educationallevel_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('certifying_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.certifyingbody')),
            ],
        ),
    ]
