# Generated by Django 4.2.3 on 2023-09-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_customuser_access_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
