# Generated by Django 4.2.3 on 2023-09-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_adminaccesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, 'registrants'), (1, 'System Admin'), (2, 'HR'), (3, 'HR Interns'), (4, 'HR Attachments')], default=0),
        ),
    ]
