# Generated by Django 4.2.3 on 2023-10-23 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_customuser_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccesslog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
