# Generated by Django 4.2.3 on 2023-10-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_adminaccesslog_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
