# Generated by Django 4.2.3 on 2023-10-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
