# Generated by Django 4.2.6 on 2023-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_customuser_staff_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trials',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
