# Generated by Django 4.2.6 on 2023-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_customuser_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
