# Generated by Django 4.2.6 on 2023-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_customuser_is_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trials',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
