# Generated by Django 4.2.3 on 2023-10-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_county_gender_maritalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
