# Generated by Django 4.2.3 on 2023-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_resume_gender_alter_resume_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
