# Generated by Django 4.2.4 on 2023-10-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_resume_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='religeon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
