# Generated by Django 4.2.4 on 2023-10-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_body',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
