# Generated by Django 4.2.3 on 2023-11-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_membership_membership_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='function',
            field=models.PositiveIntegerField(choices=[(0, 'Not Specified'), (1, 'System Admin'), (2, 'HR'), (3, 'Post'), (4, 'Publish'), (5, 'Shortlist')], default=0),
        ),
    ]
