# Generated by Django 4.2.4 on 2024-01-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_customuser_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtherstudies',
            name='certifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.educationallevel'),
        ),
    ]
