# Generated by Django 4.2.4 on 2024-01-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_furtherstudies_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
