# Generated by Django 4.2.4 on 2024-01-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_customuser_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiceducation',
            name='index_number',
        ),
    ]
