# Generated by Django 4.2.4 on 2024-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_alter_basiceducation_certification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='county',
            new_name='county_of_birth',
        ),
        migrations.AddField(
            model_name='resume',
            name='county_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='disability',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
