# Generated by Django 4.2.3 on 2024-06-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_rename_county_resume_county_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiceducation',
            name='certification',
            field=models.CharField(blank=True, choices=[('KCSE', 'Kenya Certificate of Secondary Education (KCSE)'), ('KCPE', 'Kenya Certificate of Primary Education (KCPE)')], default='KCSE', max_length=10, null=True),
        ),
    ]
