# Generated by Django 4.2.3 on 2024-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_basiceducation_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_body',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
