# Generated by Django 4.2.4 on 2024-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_membership_membership_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
