# Generated by Django 4.2.4 on 2024-07-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_resume_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='function',
            field=models.PositiveIntegerField(choices=[(0, 'No Previllages'), (1, 'System Admin'), (2, 'HR'), (3, 'Post'), (4, 'Publish'), (5, 'Shortlist')], default=0),
        ),
    ]
