# Generated by Django 4.2.4 on 2024-08-04 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_customuser_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_level',
            field=models.PositiveIntegerField(choices=[(0, 'Job Seeker'), (1, 'System Admin'), (2, 'HR'), (3, 'HR Interns'), (4, 'HR Attachments'), (5, 'staffs')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='function',
            field=models.PositiveIntegerField(choices=[(0, 'No Previllages'), (1, 'Hr-General'), (2, 'Hr-Post Jobs(Internal/External)'), (3, 'Hr-Post Internship/Attachment'), (4, 'Hr-Publsh Jobs(Internal/External)'), (5, 'Hr-Publish Internship/Attachment'), (6, 'Hr-Edit Jobs(Internal/External)'), (7, 'Hr-Edit Internship/Attachment'), (8, 'Hr-Delete Jobs(Internal/External)'), (9, 'Hr-Delete Internship/Attachment'), (10, 'ICT')], default=0),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
