# Generated by Django 4.2.3 on 2023-08-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=255)),
                ('vacancy_ref', models.CharField(max_length=50, unique=True)),
                ('job_summary', models.TextField()),
                ('job_description', models.TextField()),
                ('reports_to', models.CharField(max_length=255, unique=True)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('posts_needed', models.PositiveIntegerField()),
                ('min_work_experience', models.PositiveIntegerField()),
                ('min_educational_level', models.CharField(max_length=255)),
                ('vacancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.jobdiscipline')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=255)),
                ('vacancy_ref', models.CharField(max_length=50, unique=True)),
                ('job_summary', models.TextField()),
                ('job_description', models.TextField()),
                ('reports_to', models.CharField(max_length=255, unique=True)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('posts_needed', models.PositiveIntegerField()),
                ('min_work_experience', models.PositiveIntegerField()),
                ('min_educational_level', models.CharField(max_length=255)),
                ('vacancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.jobdiscipline')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=255)),
                ('vacancy_ref', models.CharField(max_length=50, unique=True)),
                ('job_summary', models.TextField()),
                ('job_description', models.TextField()),
                ('reports_to', models.CharField(max_length=255, unique=True)),
                ('date_open', models.DateField()),
                ('date_close', models.DateField()),
                ('posts_needed', models.PositiveIntegerField()),
                ('min_work_experience', models.PositiveIntegerField()),
                ('min_educational_level', models.CharField(max_length=255)),
                ('vacancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.jobdiscipline')),
            ],
        ),
    ]
