# Generated by Django 4.2.3 on 2023-08-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_min_educational_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
