# Generated by Django 4.2.3 on 2023-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_vacancy_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='reports_to',
            field=models.CharField(max_length=255),
        ),
    ]
