# Generated by Django 4.2.3 on 2023-08-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
