# Generated by Django 4.2.3 on 2023-08-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_access_level'),
        ('vacancies', '0005_attachment_published_internship_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='min_educational_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.educationallevel'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='min_educational_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.educationallevel'),
        ),
    ]
