# Generated by Django 4.2.4 on 2023-08-23 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0007_alter_attachment_reports_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.CharField(max_length=20)),
                ('qualify', models.BooleanField(default=False)),
                ('shortlisted', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='internship',
            name='min_educational_level',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='vacancy_type',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='job_summary',
            new_name='position_responsibilities',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_ref',
            new_name='ref',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='job_discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.jobdiscipline'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('vacancy', 'Vacancy'), ('internship', 'Internship'), ('attachment', 'Attachment')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
