# Generated by Django 4.2.4 on 2023-08-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_application_remove_internship_min_educational_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy'),
        ),
    ]
