# Generated by Django 4.2.3 on 2023-08-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_remove_application_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='highest_educational_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='work_experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
