# Generated by Django 4.2.3 on 2023-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_application_highest_educational_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
