# Generated by Django 4.2.3 on 2023-09-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_application_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
