# Generated by Django 4.2.3 on 2023-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_application_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('vacancy', 'Employment'), ('internship', 'Internship'), ('attachment', 'Attachment')], max_length=20),
        ),
    ]
