# Generated by Django 4.2.3 on 2023-09-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_vacancy_vacancy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('Employment', 'Employment'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], max_length=20),
        ),
    ]
