# Generated by Django 4.2.3 on 2023-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_alter_vacancy_vacancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='certifications_required',
            field=models.BooleanField(default=False),
        ),
    ]
