# Generated by Django 4.2.3 on 2023-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_vacancy_certifications_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='college_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Employment', 'Employment'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], max_length=20),
        ),
    ]
