# Generated by Django 4.2.6 on 2023-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_alter_application_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disqualification_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
