# Generated by Django 4.2.6 on 2023-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_application_disqualification_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
