# Generated by Django 4.2.4 on 2023-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Employment', 'Career'), ('Internship', 'Internship'), ('Attachment', 'Attachment')], max_length=20),
        ),
    ]
