# Generated by Django 4.2.3 on 2023-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_alter_vacancy_vacancy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='membership_required',
            field=models.BooleanField(default=False),
        ),
    ]
