# Generated by Django 4.2.3 on 2023-11-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0021_vacancy_membership_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='read',
        ),
        migrations.CreateModel(
            name='UserAcceptedTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.terms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
