# Generated by Django 4.2.3 on 2023-11-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_remove_terms_read_useracceptedterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
