# Generated by Django 4.2.4 on 2024-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0023_application_months_application_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
