# Generated by Django 4.2.4 on 2024-01-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0024_terms_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terms',
            name='is_read',
        ),
    ]
