# Generated by Django 4.2.4 on 2024-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0025_remove_terms_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracceptedterms',
            name='terms',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacancies.terms'),
        ),
    ]
