# Generated by Django 4.2.3 on 2024-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0027_remove_useracceptedterms_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
