# Generated by Django 4.2.3 on 2024-03-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0028_vacancy_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
