# Generated by Django 4.2.3 on 2024-03-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0030_alter_vacancy_vacancy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_type',
        ),
    ]
