# Generated by Django 4.2.4 on 2024-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0032_jobtype_vacancy_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtype',
            name='banner',
            field=models.ImageField(blank=True, default='default/banner.jpg', null=True, upload_to='job_type_banners/'),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='icon',
            field=models.ImageField(blank=True, default='default/icon.jpg', null=True, upload_to='job_type_icons/'),
        ),
    ]
