# Generated by Django 4.2.4 on 2024-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0035_alter_jobtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
