# Generated by Django 4.2.4 on 2024-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0036_alter_application_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='hired',
            field=models.BooleanField(default=False),
        ),
    ]
