# Generated by Django 4.2.4 on 2024-08-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0038_thanksmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='term_type',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='internal', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserAcceptedTerms',
        ),
    ]
