# Generated by Django 4.2.4 on 2024-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0040_alter_terms_term_type_useracceptedterms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='term_type',
            field=models.CharField(choices=[('external', 'External'), ('internal', 'Internal')], default='internal', max_length=10),
        ),
    ]
