# Generated by Django 4.2.4 on 2024-08-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0041_alter_terms_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='banner',
            field=models.ImageField(blank=True, default='default/banner.jpg', null=True, upload_to='terms_banners/'),
        ),
    ]
