# Generated by Django 4.2.4 on 2024-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0042_terms_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
