# Generated by Django 4.2.4 on 2024-08-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0043_terms_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_close',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_open',
            field=models.DateTimeField(),
        ),
    ]
